name: Build and Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore backend

    - name: Build
      run: dotnet build backend --no-restore --configuration Release

    - name: Test
      run: dotnet test backend --no-build --configuration Release --verbosity normal